### ISSUE TITLE
Add file clean-up instructions to README

### ISSUE THREAD

**Issue by JustinTBrown** [btlcreative/bottle-silverstripe-foundation#2]
Like removing composer.json from theme directory, and renaming theme for project.

**Comment by JustinTBrown** [comment]
And changing:
- theme name from `foundation` to `[project name]`
- changing http_path in `config.rb` to newly named project theme directory

**Comment by helloimbenny** [comment]
Fixed in c15f415b9a9592dfb869adeded19d48c8716b9e8 and 27c2d9e5d33b25433787a9e72c59b92052312f78
